### ISSUE TITLE
Methodology document legal clarification

### ISSUE THREAD

**Issue by HackingThings** [scriptingxss/owasp-fstm#1]
As I was reading the document I noticed the following bullet point:
"Download builds from exposed cloud provider storage locations such as
Amazon Web Services (AWS) S3 buckets"

I would recommend that a legal clarification be added to avoid CFAA violations,
with my understanding of the CFAA, if something is accessible over the internet, it does not mean it is legal to access/download it without permission.

**Comment by scriptingxss** [comment]
Good point! Will add a clarification to the document. Thanks!

**Comment by scriptingxss** [comment]
Added. See https://scriptingxss.gitbook.io/firmware-security-testing-methodology/#stage-2-obtaining-firmware
